package com.ceng319.testsql;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class SampleData {

    public static List<FlagEntity> flagEntityList;
    static {
        flagEntityList = new ArrayList<>();
        flagEntityList.add(new FlagEntity(1  ,   "Algeria"  ,   "Africa/Africa-Algeria.png"));
        flagEntityList.add(new FlagEntity(2  ,   "Angola"  ,   "Africa/Africa-Angola.png"));
        flagEntityList.add(new FlagEntity(3  ,   "Benin"  ,   "Africa/Africa-Benin.png"));
        flagEntityList.add(new FlagEntity(4  ,   "Botswana"  ,   "Africa/Africa-Botswana.png"));
        flagEntityList.add(new FlagEntity(5  ,   "Burkina_Faso"  ,   "Africa/Africa-Burkina_Faso.png"));
        flagEntityList.add(new FlagEntity(6  ,   "Burundi"  ,   "Africa/Africa-Burundi.png"));
        flagEntityList.add(new FlagEntity(7  ,   "Cameroon"  ,   "Africa/Africa-Cameroon.png"));
        flagEntityList.add(new FlagEntity(8  ,   "Cape_Verde"  ,   "Africa/Africa-Cape_Verde.png"));
        flagEntityList.add(new FlagEntity(9  ,   "Central_African_Republic"  ,   "Africa/Africa-Central_African_Republic.png"));
        flagEntityList.add(new FlagEntity(10 ,   "Chad"  ,   "Africa/Africa-Chad.png"));
        flagEntityList.add(new FlagEntity(11 ,   "Comoros"  ,   "Africa/Africa-Comoros.png"));
        flagEntityList.add(new FlagEntity(12 ,   "Dem._Rep._of_the_Congo"  ,   "Africa/Africa-Dem._Rep._of_the_Congo.png"));
        flagEntityList.add(new FlagEntity(13 ,   "Djibouti"  ,   "Africa/Africa-Djibouti.png"));
        flagEntityList.add(new FlagEntity(14 ,   "Egypt"  ,   "Africa/Africa-Egypt.png"));
        flagEntityList.add(new FlagEntity(15 ,   "Eq._Guinea"  ,   "Africa/Africa-Eq._Guinea.png"));
        flagEntityList.add(new FlagEntity(16 ,   "Eritrea"  ,   "Africa/Africa-Eritrea.png"));
        flagEntityList.add(new FlagEntity(17 ,   "Ethiopia"  ,   "Africa/Africa-Ethiopia.png"));
        flagEntityList.add(new FlagEntity(18 ,   "Gabon"  ,   "Africa/Africa-Gabon.png"));
        flagEntityList.add(new FlagEntity(19 ,   "Gambia"  ,   "Africa/Africa-Gambia.png"));
        flagEntityList.add(new FlagEntity(20 ,   "Ghana"  ,   "Africa/Africa-Ghana.png"));
        flagEntityList.add(new FlagEntity(21 ,   "Guinea"  ,   "Africa/Africa-Guinea.png"));
        flagEntityList.add(new FlagEntity(22 ,   "Guinea_Bissau"  ,   "Africa/Africa-Guinea_Bissau.png"));
        flagEntityList.add(new FlagEntity(23 ,   "Ivory_Coast"  ,   "Africa/Africa-Ivory_Coast.png"));
        flagEntityList.add(new FlagEntity(24 ,   "Kenya"  ,   "Africa/Africa-Kenya.png"));
        flagEntityList.add(new FlagEntity(25 ,   "Lesotho"  ,   "Africa/Africa-Lesotho.png"));
        flagEntityList.add(new FlagEntity(26 ,   "Liberia"  ,   "Africa/Africa-Liberia.png"));
        flagEntityList.add(new FlagEntity(27 ,   "Libya"  ,   "Africa/Africa-Libya.png"));
        flagEntityList.add(new FlagEntity(28 ,   "Madagascar"  ,   "Africa/Africa-Madagascar.png"));
        flagEntityList.add(new FlagEntity(29 ,   "Malawi"  ,   "Africa/Africa-Malawi.png"));
        flagEntityList.add(new FlagEntity(30 ,   "Mali"  ,   "Africa/Africa-Mali.png"));
        flagEntityList.add(new FlagEntity(31 ,   "Mauritania"  ,   "Africa/Africa-Mauritania.png"));
        flagEntityList.add(new FlagEntity(32 ,   "Mauritius"  ,   "Africa/Africa-Mauritius.png"));
        flagEntityList.add(new FlagEntity(33 ,   "Morocco"  ,   "Africa/Africa-Morocco.png"));
        flagEntityList.add(new FlagEntity(34 ,   "Mozambique"  ,   "Africa/Africa-Mozambique.png"));
        flagEntityList.add(new FlagEntity(35 ,   "Namibia"  ,   "Africa/Africa-Namibia.png"));
        flagEntityList.add(new FlagEntity(36 ,   "Niger"  ,   "Africa/Africa-Niger.png"));
        flagEntityList.add(new FlagEntity(37 ,   "Nigeria"  ,   "Africa/Africa-Nigeria.png"));
        flagEntityList.add(new FlagEntity(38 ,   "Republic_of_the_Congo"  ,   "Africa/Africa-Republic_of_the_Congo.png"));
        flagEntityList.add(new FlagEntity(39 ,   "Rwanda"  ,   "Africa/Africa-Rwanda.png"));
        flagEntityList.add(new FlagEntity(40 ,   "Sao_Tome"  ,   "Africa/Africa-Sao_Tome.png"));
        flagEntityList.add(new FlagEntity(41 ,   "Senegal"  ,   "Africa/Africa-Senegal.png"));
        flagEntityList.add(new FlagEntity(42 ,   "Seychelles"  ,   "Africa/Africa-Seychelles.png"));
        flagEntityList.add(new FlagEntity(43 ,   "Sierra_Leone"  ,   "Africa/Africa-Sierra_Leone.png"));
        flagEntityList.add(new FlagEntity(44 ,   "Somalia"  ,   "Africa/Africa-Somalia.png"));
        flagEntityList.add(new FlagEntity(45 ,   "South_Africa"  ,   "Africa/Africa-South_Africa.png"));
        flagEntityList.add(new FlagEntity(46 ,   "Sudan"  ,   "Africa/Africa-Sudan.png"));
        flagEntityList.add(new FlagEntity(47 ,   "Swaziland"  ,   "Africa/Africa-Swaziland.png"));
        flagEntityList.add(new FlagEntity(48 ,   "Tanzania"  ,   "Africa/Africa-Tanzania.png"));
        flagEntityList.add(new FlagEntity(49 ,   "Togo"  ,   "Africa/Africa-Togo.png"));
        flagEntityList.add(new FlagEntity(50 ,   "Tunisia"  ,   "Africa/Africa-Tunisia.png"));
        flagEntityList.add(new FlagEntity(51 ,   "Uganda"  ,   "Africa/Africa-Uganda.png"));
        flagEntityList.add(new FlagEntity(52 ,   "Zambia"  ,   "Africa/Africa-Zambia.png"));
        flagEntityList.add(new FlagEntity(53 ,   "Zimbabwe"  ,   "Africa/Africa-Zimbabwe.png"));
        flagEntityList.add(new FlagEntity(54 ,   "Afghanistan"  ,   "Asia/Asia-Afghanistan.png"));
        flagEntityList.add(new FlagEntity(55 ,   "Armenia"  ,   "Asia/Asia-Armenia.png"));
        flagEntityList.add(new FlagEntity(56 ,   "Azerbaijan"  ,   "Asia/Asia-Azerbaijan.png"));
        flagEntityList.add(new FlagEntity(57 ,   "Bahrain"  ,   "Asia/Asia-Bahrain.png"));
        flagEntityList.add(new FlagEntity(58 ,   "Bangladesh"  ,   "Asia/Asia-Bangladesh.png"));
        flagEntityList.add(new FlagEntity(59 ,   "Bhutan"  ,   "Asia/Asia-Bhutan.png"));
        flagEntityList.add(new FlagEntity(60 ,   "Brunei"  ,   "Asia/Asia-Brunei.png"));
        flagEntityList.add(new FlagEntity(61 ,   "Cambodia"  ,   "Asia/Asia-Cambodia.png"));
        flagEntityList.add(new FlagEntity(62 ,   "China"  ,   "Asia/Asia-China.png"));
        flagEntityList.add(new FlagEntity(63 ,   "Christmas_Island"  ,   "Asia/Asia-Christmas_Island.png"));
        flagEntityList.add(new FlagEntity(64 ,   "Georgia"  ,   "Asia/Asia-Georgia.png"));
        flagEntityList.add(new FlagEntity(65 ,   "Hong_Kong"  ,   "Asia/Asia-Hong_Kong.png"));
        flagEntityList.add(new FlagEntity(66 ,   "India"  ,   "Asia/Asia-India.png"));
        flagEntityList.add(new FlagEntity(67 ,   "Indonesia"  ,   "Asia/Asia-Indonesia.png"));
        flagEntityList.add(new FlagEntity(68 ,   "Iran"  ,   "Asia/Asia-Iran.png"));
        flagEntityList.add(new FlagEntity(69 ,   "Iraq"  ,   "Asia/Asia-Iraq.png"));
        flagEntityList.add(new FlagEntity(70 ,   "Israel"  ,   "Asia/Asia-Israel.png"));
        flagEntityList.add(new FlagEntity(71 ,   "Japan"  ,   "Asia/Asia-Japan.png"));
        flagEntityList.add(new FlagEntity(72 ,   "Jordan"  ,   "Asia/Asia-Jordan.png"));
        flagEntityList.add(new FlagEntity(73 ,   "Kazakhstan"  ,   "Asia/Asia-Kazakhstan.png"));
        flagEntityList.add(new FlagEntity(74 ,   "Kuwait"  ,   "Asia/Asia-Kuwait.png"));
        flagEntityList.add(new FlagEntity(75 ,   "Kyrgyzstan"  ,   "Asia/Asia-Kyrgyzstan.png"));
        flagEntityList.add(new FlagEntity(76 ,   "Laos"  ,   "Asia/Asia-Laos.png"));
        flagEntityList.add(new FlagEntity(77 ,   "Lebanon"  ,   "Asia/Asia-Lebanon.png"));
        flagEntityList.add(new FlagEntity(78 ,   "Macao"  ,   "Asia/Asia-Macao.png"));
        flagEntityList.add(new FlagEntity(79 ,   "Malaysia"  ,   "Asia/Asia-Malaysia.png"));
        flagEntityList.add(new FlagEntity(80 ,   "Maldives"  ,   "Asia/Asia-Maldives.png"));
        flagEntityList.add(new FlagEntity(81 ,   "Mongolia"  ,   "Asia/Asia-Mongolia.png"));
        flagEntityList.add(new FlagEntity(82 ,   "Myanmar"  ,   "Asia/Asia-Myanmar.png"));
        flagEntityList.add(new FlagEntity(83 ,   "Nepal"  ,   "Asia/Asia-Nepal.png"));
        flagEntityList.add(new FlagEntity(84 ,   "North_Korea"  ,   "Asia/Asia-North_Korea.png"));
        flagEntityList.add(new FlagEntity(85 ,   "Oman"  ,   "Asia/Asia-Oman.png"));
        flagEntityList.add(new FlagEntity(86 ,   "Pakistan"  ,   "Asia/Asia-Pakistan.png"));
        flagEntityList.add(new FlagEntity(87 ,   "Philippines"  ,   "Asia/Asia-Philippines.png"));
        flagEntityList.add(new FlagEntity(88 ,   "Qatar"  ,   "Asia/Asia-Qatar.png"));
        flagEntityList.add(new FlagEntity(89 ,   "Saudi_Arabia"  ,   "Asia/Asia-Saudi_Arabia.png"));
        flagEntityList.add(new FlagEntity(90 ,   "Singapore"  ,   "Asia/Asia-Singapore.png"));
        flagEntityList.add(new FlagEntity(91 ,   "South_Georgia"  ,   "Asia/Asia-South_Georgia.png"));
        flagEntityList.add(new FlagEntity(92 ,   "South_Korea"  ,   "Asia/Asia-South_Korea.png"));
        flagEntityList.add(new FlagEntity(93 ,   "Sri_Lanka"  ,   "Asia/Asia-Sri_Lanka.png"));
        flagEntityList.add(new FlagEntity(94 ,   "Syria"  ,   "Asia/Asia-Syria.png"));
        flagEntityList.add(new FlagEntity(95 ,   "Taiwan"  ,   "Asia/Asia-Taiwan.png"));
        flagEntityList.add(new FlagEntity(96 ,   "Tajikistan"  ,   "Asia/Asia-Tajikistan.png"));
        flagEntityList.add(new FlagEntity(97 ,   "Thailand"  ,   "Asia/Asia-Thailand.png"));
        flagEntityList.add(new FlagEntity(98 ,   "Tibet"  ,   "Asia/Asia-Tibet.png"));
        flagEntityList.add(new FlagEntity(99 ,   "Timor-Leste"  ,   "Asia/Asia-Timor-Leste.png"));
        flagEntityList.add(new FlagEntity(100,   "Turkey"  ,   "Asia/Asia-Turkey.png"));
        flagEntityList.add(new FlagEntity(101,   "Turkmenistan"  ,   "Asia/Asia-Turkmenistan.png"));
        flagEntityList.add(new FlagEntity(102,   "UAE"  ,   "Asia/Asia-UAE.png"));
        flagEntityList.add(new FlagEntity(103,   "Uzbekistan"  ,   "Asia/Asia-Uzbekistan.png"));
        flagEntityList.add(new FlagEntity(104,   "Vietnam"  ,   "Asia/Asia-Vietnam.png"));
        flagEntityList.add(new FlagEntity(105,   "Yemen"  ,   "Asia/Asia-Yemen.png"));
        flagEntityList.add(new FlagEntity(106,   "Albania"  ,   "Europe/Europe-Albania.png"));
        flagEntityList.add(new FlagEntity(107,   "Andorra"  ,   "Europe/Europe-Andorra.png"));
        flagEntityList.add(new FlagEntity(108,   "Austria"  ,   "Europe/Europe-Austria.png"));
        flagEntityList.add(new FlagEntity(109,   "Belarus"  ,   "Europe/Europe-Belarus.png"));
        flagEntityList.add(new FlagEntity(110,   "Belgium"  ,   "Europe/Europe-Belgium.png"));
        flagEntityList.add(new FlagEntity(111,   "Bosnia"  ,   "Europe/Europe-Bosnia.png"));
        flagEntityList.add(new FlagEntity(112,   "Bulgaria"  ,   "Europe/Europe-Bulgaria.png"));
        flagEntityList.add(new FlagEntity(113,   "Croatia"  ,   "Europe/Europe-Croatia.png"));
        flagEntityList.add(new FlagEntity(114,   "Cyprus"  ,   "Europe/Europe-Cyprus.png"));
        flagEntityList.add(new FlagEntity(115,   "Czech_Republic"  ,   "Europe/Europe-Czech_Republic.png"));
        flagEntityList.add(new FlagEntity(116,   "Denmark"  ,   "Europe/Europe-Denmark.png"));
        flagEntityList.add(new FlagEntity(117,   "Estonia"  ,   "Europe/Europe-Estonia.png"));
        flagEntityList.add(new FlagEntity(118,   "Faroe_Islands"  ,   "Europe/Europe-Faroe_Islands.png"));
        flagEntityList.add(new FlagEntity(119,   "Finland"  ,   "Europe/Europe-Finland.png"));
        flagEntityList.add(new FlagEntity(120,   "France"  ,   "Europe/Europe-France.png"));
        flagEntityList.add(new FlagEntity(121,   "Germany"  ,   "Europe/Europe-Germany.png"));
        flagEntityList.add(new FlagEntity(122,   "Gibraltar"  ,   "Europe/Europe-Gibraltar.png"));
        flagEntityList.add(new FlagEntity(123,   "Greece"  ,   "Europe/Europe-Greece.png"));
        flagEntityList.add(new FlagEntity(124,   "Greenland"  ,   "Europe/Europe-Greenland.png"));
        flagEntityList.add(new FlagEntity(125,   "Hungary"  ,   "Europe/Europe-Hungary.png"));
        flagEntityList.add(new FlagEntity(126,   "Iceland"  ,   "Europe/Europe-Iceland.png"));
        flagEntityList.add(new FlagEntity(127,   "Ireland"  ,   "Europe/Europe-Ireland.png"));
        flagEntityList.add(new FlagEntity(128,   "Italy"  ,   "Europe/Europe-Italy.png"));
        flagEntityList.add(new FlagEntity(129,   "Latvia"  ,   "Europe/Europe-Latvia.png"));
        flagEntityList.add(new FlagEntity(130,   "Liechtenstein"  ,   "Europe/Europe-Liechtenstein.png"));
        flagEntityList.add(new FlagEntity(131,   "Lithuania"  ,   "Europe/Europe-Lithuania.png"));
        flagEntityList.add(new FlagEntity(132,   "Luxembourg"  ,   "Europe/Europe-Luxembourg.png"));
        flagEntityList.add(new FlagEntity(133,   "Macedonia"  ,   "Europe/Europe-Macedonia.png"));
        flagEntityList.add(new FlagEntity(134,   "Malta"  ,   "Europe/Europe-Malta.png"));
        flagEntityList.add(new FlagEntity(135,   "Moldova"  ,   "Europe/Europe-Moldova.png"));
        flagEntityList.add(new FlagEntity(136,   "Monaco"  ,   "Europe/Europe-Monaco.png"));
        flagEntityList.add(new FlagEntity(137,   "Netherlands"  ,   "Europe/Europe-Netherlands.png"));
        flagEntityList.add(new FlagEntity(138,   "Norway"  ,   "Europe/Europe-Norway.png"));
        flagEntityList.add(new FlagEntity(139,   "Poland"  ,   "Europe/Europe-Poland.png"));
        flagEntityList.add(new FlagEntity(140,   "Portugal"  ,   "Europe/Europe-Portugal.png"));
        flagEntityList.add(new FlagEntity(141,   "Romania"  ,   "Europe/Europe-Romania.png"));
        flagEntityList.add(new FlagEntity(142,   "Russian_Federation"  ,   "Europe/Europe-Russian_Federation.png"));
        flagEntityList.add(new FlagEntity(143,   "San_Marino"  ,   "Europe/Europe-San_Marino.png"));
        flagEntityList.add(new FlagEntity(144,   "Serbia_and_Montenegro"  ,   "Europe/Europe-Serbia_and_Montenegro.png"));
        flagEntityList.add(new FlagEntity(145,   "Slovakia"  ,   "Europe/Europe-Slovakia.png"));
        flagEntityList.add(new FlagEntity(146,   "Slovenia"  ,   "Europe/Europe-Slovenia.png"));
        flagEntityList.add(new FlagEntity(147,   "Soviet_Union"  ,   "Europe/Europe-Soviet_Union.png"));
        flagEntityList.add(new FlagEntity(148,   "Spain"  ,   "Europe/Europe-Spain.png"));
        flagEntityList.add(new FlagEntity(149,   "Sweden"  ,   "Europe/Europe-Sweden.png"));
        flagEntityList.add(new FlagEntity(150,   "Switzerland"  ,   "Europe/Europe-Switzerland.png"));
        flagEntityList.add(new FlagEntity(151,   "Ukraine"  ,   "Europe/Europe-Ukraine.png"));
        flagEntityList.add(new FlagEntity(152,   "United_Kingdom"  ,   "Europe/Europe-United_Kingdom.png"));
        flagEntityList.add(new FlagEntity(153,   "Vatican_City"  ,   "Europe/Europe-Vatican_City.png"));
        flagEntityList.add(new FlagEntity(154,   "Anguilla"  ,   "North_America/North_America-Anguilla.png"));
        flagEntityList.add(new FlagEntity(155,   "Antigua_and_Barbuda"  ,   "North_America/North_America-Antigua_and_Barbuda.png"));
        flagEntityList.add(new FlagEntity(156,   "Aruba"  ,   "North_America/North_America-Aruba.png"));
        flagEntityList.add(new FlagEntity(157,   "Bahamas"  ,   "North_America/North_America-Bahamas.png"));
        flagEntityList.add(new FlagEntity(158,   "Barbados"  ,   "North_America/North_America-Barbados.png"));
        flagEntityList.add(new FlagEntity(159,   "Belize"  ,   "North_America/North_America-Belize.png"));
        flagEntityList.add(new FlagEntity(160,   "Bermuda"  ,   "North_America/North_America-Bermuda.png"));
        flagEntityList.add(new FlagEntity(161,   "British_Virgin_Islands"  ,   "North_America/North_America-British_Virgin_Islands.png"));
        flagEntityList.add(new FlagEntity(162,   "Canada"  ,   "North_America/North_America-Canada.png"));
        flagEntityList.add(new FlagEntity(163,   "Cayman_Islands"  ,   "North_America/North_America-Cayman_Islands.png"));
        flagEntityList.add(new FlagEntity(164,   "Costa_Rica"  ,   "North_America/North_America-Costa_Rica.png"));
        flagEntityList.add(new FlagEntity(165,   "Cuba"  ,   "North_America/North_America-Cuba.png"));
        flagEntityList.add(new FlagEntity(166,   "Dominica"  ,   "North_America/North_America-Dominica.png"));
        flagEntityList.add(new FlagEntity(167,   "Dominican_Republic"  ,   "North_America/North_America-Dominican_Republic.png"));
        flagEntityList.add(new FlagEntity(168,   "El_Salvador"  ,   "North_America/North_America-El_Salvador.png"));
        flagEntityList.add(new FlagEntity(169,   "Grenada"  ,   "North_America/North_America-Grenada.png"));
        flagEntityList.add(new FlagEntity(170,   "Guatemala"  ,   "North_America/North_America-Guatemala.png"));
        flagEntityList.add(new FlagEntity(171,   "Haiti"  ,   "North_America/North_America-Haiti.png"));
        flagEntityList.add(new FlagEntity(172,   "Honduras"  ,   "North_America/North_America-Honduras.png"));
        flagEntityList.add(new FlagEntity(173,   "Jamaica"  ,   "North_America/North_America-Jamaica.png"));
        flagEntityList.add(new FlagEntity(174,   "Martinique"  ,   "North_America/North_America-Martinique.png"));
        flagEntityList.add(new FlagEntity(175,   "Mexico"  ,   "North_America/North_America-Mexico.png"));
        flagEntityList.add(new FlagEntity(176,   "Montserrat"  ,   "North_America/North_America-Montserrat.png"));
        flagEntityList.add(new FlagEntity(177,   "Nicaragua"  ,   "North_America/North_America-Nicaragua.png"));
        flagEntityList.add(new FlagEntity(178,   "Panama"  ,   "North_America/North_America-Panama.png"));
        flagEntityList.add(new FlagEntity(179,   "Puerto_Rico"  ,   "North_America/North_America-Puerto_Rico.png"));
        flagEntityList.add(new FlagEntity(180,   "Saint_Kitts_and_Nevis"  ,   "North_America/North_America-Saint_Kitts_and_Nevis.png"));
        flagEntityList.add(new FlagEntity(181,   "Saint_Lucia"  ,   "North_America/North_America-Saint_Lucia.png"));
        flagEntityList.add(new FlagEntity(182,   "Saint_Pierre"  ,   "North_America/North_America-Saint_Pierre.png"));
        flagEntityList.add(new FlagEntity(183,   "St._Vicent_and_Grenadines"  ,   "North_America/North_America-St._Vicent_and_Grenadines.png"));
        flagEntityList.add(new FlagEntity(184,   "Turks_and_Caicos_Islands"  ,   "North_America/North_America-Turks_and_Caicos_Islands.png"));
        flagEntityList.add(new FlagEntity(185,   "United_States_of_America"  ,   "North_America/North_America-United_States_of_America.png"));
        flagEntityList.add(new FlagEntity(186,   "US_Virgin_Islands"  ,   "North_America/North_America-US_Virgin_Islands.png"));
        flagEntityList.add(new FlagEntity(187,   "American_Samoa"  ,   "Oceania/Oceania-American_Samoa.png"));
        flagEntityList.add(new FlagEntity(188,   "Australia"  ,   "Oceania/Oceania-Australia.png"));
        flagEntityList.add(new FlagEntity(189,   "Cook_Islands"  ,   "Oceania/Oceania-Cook_Islands.png"));
        flagEntityList.add(new FlagEntity(190,   "Fiji"  ,   "Oceania/Oceania-Fiji.png"));
        flagEntityList.add(new FlagEntity(191,   "Guam"  ,   "Oceania/Oceania-Guam.png"));
        flagEntityList.add(new FlagEntity(192,   "Kiribati"  ,   "Oceania/Oceania-Kiribati.png"));
        flagEntityList.add(new FlagEntity(193,   "Marshall_Islands"  ,   "Oceania/Oceania-Marshall_Islands.png"));
        flagEntityList.add(new FlagEntity(194,   "Micronesia"  ,   "Oceania/Oceania-Micronesia.png"));
        flagEntityList.add(new FlagEntity(195,   "Nauru"  ,   "Oceania/Oceania-Nauru.png"));
        flagEntityList.add(new FlagEntity(196,   "New_Zealand"  ,   "Oceania/Oceania-New_Zealand.png"));
        flagEntityList.add(new FlagEntity(197,   "Niue"  ,   "Oceania/Oceania-Niue.png"));
        flagEntityList.add(new FlagEntity(198,   "Norfolk_Island"  ,   "Oceania/Oceania-Norfolk_Island.png"));
        flagEntityList.add(new FlagEntity(199,   "Palau"  ,   "Oceania/Oceania-Palau.png"));
        flagEntityList.add(new FlagEntity(200,   "Papua_New_Guinea"  ,   "Oceania/Oceania-Papua_New_Guinea.png"));
        flagEntityList.add(new FlagEntity(201,   "Pitcairn_Islands"  ,   "Oceania/Oceania-Pitcairn_Islands.png"));
        flagEntityList.add(new FlagEntity(202,   "Samoa"  ,   "Oceania/Oceania-Samoa.png"));
        flagEntityList.add(new FlagEntity(203,   "Soloman_Islands"  ,   "Oceania/Oceania-Soloman_Islands.png"));
        flagEntityList.add(new FlagEntity(204,   "Tonga"  ,   "Oceania/Oceania-Tonga.png"));
        flagEntityList.add(new FlagEntity(205,   "Tuvalu"  ,   "Oceania/Oceania-Tuvalu.png"));
        flagEntityList.add(new FlagEntity(206,   "Vanuatu"  ,   "Oceania/Oceania-Vanuatu.png"));
        flagEntityList.add(new FlagEntity(207,   "Wallis_and_Futuna"  ,   "Oceania/Oceania-Wallis_and_Futuna.png"));
        flagEntityList.add(new FlagEntity(208,   "Argentina"  ,   "South_America/South_America-Argentina.png"));
        flagEntityList.add(new FlagEntity(209,   "Bolivia"  ,   "South_America/South_America-Bolivia.png"));
        flagEntityList.add(new FlagEntity(210,   "Brazil"  ,   "South_America/South_America-Brazil.png"));
        flagEntityList.add(new FlagEntity(211,   "Chile"  ,   "South_America/South_America-Chile.png"));
        flagEntityList.add(new FlagEntity(212,   "Colombia"  ,   "South_America/South_America-Colombia.png"));
        flagEntityList.add(new FlagEntity(213,   "Ecuador"  ,   "South_America/South_America-Ecuador.png"));
        flagEntityList.add(new FlagEntity(214,   "Falkland_Islands"  ,   "South_America/South_America-Falkland_Islands.png"));
        flagEntityList.add(new FlagEntity(215,   "French_Polynesia"  ,   "South_America/South_America-French_Polynesia.png"));
        flagEntityList.add(new FlagEntity(216,   "Guyana"  ,   "South_America/South_America-Guyana.png"));
        flagEntityList.add(new FlagEntity(217,   "Netherlands_Antilles"  ,   "South_America/South_America-Netherlands_Antilles.png"));
        flagEntityList.add(new FlagEntity(218,   "Paraguay"  ,   "South_America/South_America-Paraguay.png"));
        flagEntityList.add(new FlagEntity(219,   "Peru"  ,   "South_America/South_America-Peru.png"));
        flagEntityList.add(new FlagEntity(220,   "Suriname"  ,   "South_America/South_America-Suriname.png"));
        flagEntityList.add(new FlagEntity(221,   "Trinidad_and_Tobago"  ,   "South_America/South_America-Trinidad_and_Tobago.png"));
        flagEntityList.add(new FlagEntity(222,   "Uruguay"  ,   "South_America/South_America-Uruguay.png"));
        flagEntityList.add(new FlagEntity(223,   "Venezuela"  ,   "South_America/South_America-Venezuela.png"));
    }

    private void generateList(){
        File folder = new File("your/path");

        File[] listOfFiles = folder.listFiles();

        for (int i = 0; i < listOfFiles.length; i++) {
            if (listOfFiles[i].isFile()) {
                System.out.println("File " + listOfFiles[i].getName());
            } else if (listOfFiles[i].isDirectory()) {
                System.out.println("Directory " + listOfFiles[i].getName());
            }
        }
    }
}
